name: Unit Tests

on:
  workflow_call:
    inputs:
      macos-runner:
        required: true
        type: string
      xcode-version:
        required: false
        type: string

jobs:
  unit-tests:
    name: "macOS on ${{ inputs.macos-runner }}"
    runs-on: ${{ inputs.macos-runner }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ inputs.xcode-version || '26.2' }}
      - name: Setup environment
        run: make setup
      - name: Setup Cache
        id: model-cache
        uses: actions/cache@v4
        with:
          path: Models
          key: ${{ runner.os }}-models
      - name: Download Models
        if: steps.model-cache.outputs.cache-hit != 'true'
        run: make download-model MODEL=tiny
      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild clean build-for-testing -scheme whisperkit-Package -destination 'platform=macOS,arch=arm64' | xcpretty
          xcodebuild test -testPlan UnitTestsPlan -scheme whisperkit-Package -destination 'platform=macOS,arch=arm64'
      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-macOS-on-${{ inputs.macos-runner }}
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
          retention-days: 5
